eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
  healthcheck:
    enabled: true

server:
  port: 9000

endpoints:
  enabled: true
  actuator:
    enabled: true
  shutdown:
    enabled: false

spring:
  application.name: gateway


zuul.routes:
  http:
    path: /http/**
    serviceId: http_worker
  storage:
    paht: /storage/**
    serviceId: storage